### ISSUE TITLE
本地题库

### ISSUE THREAD

**Issue by RichY0608** [SocialSisterYi/CxKitty#114]
本地题库不会配置 能否教一下 下午考试 都是原题 时间不够搜 给一个现成的看一下 麻烦了大佬

**Comment by RichY0608** [comment]
json的正确格式 麻烦给个样本

**Comment by SocialSisterYi** [comment]
在 config.yml 中修改下面这部分配置，这里以当前路径下的`questions.json`为例

```yaml
searchers:
  # 本地 JSON 数据库搜索器 (key为题, value为答案)
  - type: jsonFileSearcher
     file_path: "questions.json"  # 数据库文件路径
```

在 question.json 中，以 key 作为匹配的题干，value 作为题干的答案，如：

```json
{
    "问题": "答案"
}
```
