### ISSUE TITLE
支持 Python 3.11

### ISSUE THREAD

**Issue by H2Sxxa** [SocialSisterYi/CxKitty#90]
把项目拉下来在本地跑了一下，`poetry`安装的时候不支持`3.11`，更换了一下依赖版本，似乎可以正常运行，不清楚有没有什么其他的BUG

```toml
python = ">=3.10,<3.12"
...
ddddocr = "^1.4.9"
```
